version: "3.4"
services:
  test-runner:
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        SSH_PUBLIC_KEY: $SSH_PUBLIC_KEY
    container_name: test-runner
    environment:
      - SSH_PUBLIC_KEY=$SSH_PUBLIC_KEY
    ports:
      - '2222:2222'
