name: Deploy Crusher app

on:
  release:
    types: [published, edited]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 12.19.1

      - name: Install yarn
        run: npm install -g yarn

      - name: Create ecosystem.config.js
        run: cp ecosystem.config.sample.js ecosystem.config.js

      - name: Use cache for yarn if available
        uses: c-hive/gha-yarn-cache@v1

      - name: Install yarn dependencies
        run: yarn install

      - name: Setup crusher
        run: yarn setup:ee

      - name: Package crusher-app for deployment
        env:
          EXTENSION_ID: gfiagiidgjjnmklhbalcjbmdjbpphdln
          NEXT_PUBLIC_GITHUB_APP_CLIENT_ID: Iv1.b94bab70cd7aad37
          NEXT_PUBLIC_BACKEND_URL: https://backend.crusher.dev/
          NEXT_PUBLIC_FRONTEND_URL: https://app.crusher.dev/
        run: sh scripts/vercel-package.sh

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          working-directory: output/crusher-app
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS:  true
